In [465]:
# Load pandas.
import pandas as pd

In [466]:
# Load the raw products file into a dataframe we can clean.
product = pd.DataFrame(pd.read_csv('products.csv'))
df_product = product.copy()

Structure: shape & data type

In [467]:
# Check the shape and column types.
df_product.shape
df_product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19326 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          19326 non-null  object
 1   name         19326 non-null  object
 2   desc         19319 non-null  object
 3   price        19280 non-null  object
 4   promo_price  19326 non-null  object
 5   in_stock     19326 non-null  int64
 6   type         19276 non-null  object
dtypes: int64(1), object(6)
memory usage: 1.0+ MB

Remove whitespace from all string colomns

In [468]:
# Strip stray whitespace from the text columns.
df_product['name'].str.strip()
df_product['desc'].str.strip()
df_product['type'].str.strip()

0            8696
1        13855401
2            1387
3            1230
4            1364
           ...
19321       12282
19322        1392
19323        1392
19324        1392
19325        1392
Name: type, Length: 19326, dtype: object

Drop exact duplicate rows

In [469]:
# Count how many rows are exact duplicates.
df_product.duplicated().sum()

np.int64(8746)

In [470]:
# Look at those duplicate rows.
df_product[df_product.duplicated()]

,sku,name,desc,price,promo_price,in_stock,type
101,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199,11.455.917,0,1282
102,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199,11.455.917,0,1282
103,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199,11.455.917,0,1282
104,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199,11.455.917,0,1282
105,APP0390,"Apple MacBook Pro 133 ""Core i5 25GHz | 4GB RAM...",MacBook Pro laptop 133 inches (MD101Y / A).,1199,11.455.917,0,1282
...,...,...,...,...,...,...,...
16831,APP2302,"Apple MacBook Pro 13 ""Core i5 Touch Bar 33GHz ...",New MacBook Pro 13-inch Core i5 Touch Bar 33 G...,26.155.941,26.155.941,0,"1,02E+12"
16833,APP2303,"Apple MacBook Pro 13 ""Core i5 Touch Bar 33GHz ...",New MacBook Pro 13 inch Touch Bar 33 GHz Core ...,237.559.421,23.755.942,0,"1,02E+12"
18190,PAR0077,Parrot Bebop Drone 2 Power,Drone cuadricóptero quality camera integrated ...,699.9,6.733.892,0,11905404
18308,NKI0010,Nokia Wireless sphygmomanometer Plata,Sphygmomanometer for iPhone iPad and iPod App.,129.99,1.149.899,1,11905404
18514,PLA0035,Bluetooth Headset Plantronics Explorer 80,egonómico wireless headset design for iPhone i...,39.99,349.896,1,5384

Drop duplicates that has all colomns same

In [471]:
# Drop the exact duplicate rows.
df_product = df_product.drop_duplicates()

every SKU should be unique - one row per product. Found: only APP1197 still had two rows, identical in every column except one had price = NaN

In [472]:
# Check for any SKU that still shows up more than once.
df_product[df_product['sku'].duplicated()]

,sku,name,desc,price,promo_price,in_stock,type
8000,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,NaN,1305.59,0,1282

See how It looks ?

In [473]:
# Look at both rows for that SKU side by side.
df_product[df_product['sku'] == 'APP1197']

,sku,name,desc,price,promo_price,in_stock,type
7992,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,1729,1305.59,0,1282
8000,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,NaN,1305.59,0,1282

Drop duplicates with subset 'sku' and kepp first raw

In [474]:
# Keep only the first row for each SKU, drop the rest.
df_product = df_product.drop_duplicates(subset='sku', keep='first')

Check Again !

In [475]:
# Check that SKU again -- should be just one row now.
df_product[df_product['sku'] == 'APP1197']

,sku,name,desc,price,promo_price,in_stock,type
7992,APP1197,"Apple iMac 21.5 ""Core i5 31 GHz Retina display...",Desktop Apple iMac 21.5 inch i5 31 GHz Retina ...,1729,1305.59,0,1282

Missing Values ?

In [476]:
# Check for missing values in each column.
df_product.isna().sum()

sku             0
name            0
desc            7
price          45
promo_price     0
in_stock        0
type           50
dtype: int64

What percentage ?

In [477]:
# See what share of desc values are missing.
df_product['desc'].isna().value_counts(normalize = True)

desc
False    0.999338
True     0.000662
Name: proportion, dtype: float64

Nan desc's are replaced by their 'name'

In [478]:
# Fill missing desc with the product's name instead.
df_product['desc'] = df_product['desc'].fillna(df_product['name'])

Check! if Nan remains in 'desc'

In [479]:
# Check the columns after that fix.
df_product.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10579 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          10579 non-null  object
 1   name         10579 non-null  object
 2   desc         10579 non-null  object
 3   price        10534 non-null  object
 4   promo_price  10579 non-null  object
 5   in_stock     10579 non-null  int64
 6   type         10529 non-null  object
dtypes: int64(1), object(6)
memory usage: 661.2+ KB

In [480]:
# See what share of price values are missing.
df_product['price'].isna().value_counts(normalize = True)

price
False    0.995746
True     0.004254
Name: proportion, dtype: float64

In [481]:
# See what share of type values are missing.
df_product['type'].isna().value_counts(normalize = True)

type
False    0.995274
True     0.004726
Name: proportion, dtype: float64

put 'missing' for Nan values of column 'type'

In [482]:
# Fill missing type values with 'missing'.
df_product['type'] = df_product['type'].fillna('missing')

Check!

In [483]:
# Check the columns again.
df_product.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10579 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          10579 non-null  object
 1   name         10579 non-null  object
 2   desc         10579 non-null  object
 3   price        10534 non-null  object
 4   promo_price  10579 non-null  object
 5   in_stock     10579 non-null  int64
 6   type         10579 non-null  object
dtypes: int64(1), object(6)
memory usage: 661.2+ KB

Drop Nan values from the colomns [desc, price, type]

In [484]:
# Drop whatever rows still have missing values.
df_product = df_product.dropna(axis = 0)

Check Again !

In [485]:
# Confirm nothing is missing now.
df_product.isna().sum()

sku            0
name           0
desc           0
price          0
promo_price    0
in_stock       0
type           0
dtype: int64

Fix price type (3.5 % of data has wrong price)

In [486]:
# (Tried converting price to numbers directly -- didn't work, left as a note.)
#pd.to_numeric(df_product['price'])

What % is for two .'s entries in price ?

In [487]:
# Check how many decimal points show up in the price text.
df_product['price'].str.count(r'\.').value_counts(normalize =  True)

price
1    0.659009
0    0.305202
2    0.035789
Name: proportion, dtype: float64

Data type conversion for price column

In [488]:
# Force price to numbers -- bad formats become NaN.
numeric_attempt = pd.to_numeric(df_product['price'], errors='coerce')

Check! what amount is converted to Nan ?

In [489]:
# See what share of prices failed to convert.
numeric_attempt.isna().value_counts(normalize = True)

price
False    0.964211
True     0.035789
Name: proportion, dtype: float64

Check ! the values need to drop from column price

In [490]:
# Look at the price values that failed to convert.
failed = df_product['price'][numeric_attempt.isna() & df_product['price'].notna()]
failed
df_product[['price']][numeric_attempt.isna() & df_product['price'].notna()]

           price
665    1.639.792
792    4.694.994
797    4.090.042
827    2.199.791
885    5.609.698
...          ...
19312  6.999.003
19313  6.999.003
19314  6.999.003
19315  6.999.003
19316  6.999.003

[377 rows x 1 columns]

Apply pd.to_numeric to data frame and reassign the coloumn 'price'

In [491]:
# Convert price to a proper number.
df_product['price'] = pd.to_numeric(df_product['price'], errors='coerce')

Check! How many values are converted to Nan ?

In [492]:
# Check again what share is missing now.
df_product['price'].isna().value_counts(normalize = True)

price
False    0.964211
True     0.035789
Name: proportion, dtype: float64

Drop all Nan values form 'price' column

In [493]:
# Drop the rows where price never converted.
df_product = df_product.dropna(axis =0)

Check again: info()

In [494]:
# Check the columns after that.
df_product.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10157 entries, 0 to 19325
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku          10157 non-null  object
 1   name         10157 non-null  object
 2   desc         10157 non-null  object
 3   price        10157 non-null  float64
 4   promo_price  10157 non-null  object
 5   in_stock     10157 non-null  int64
 6   type         10157 non-null  object
dtypes: float64(1), int64(1), object(5)
memory usage: 634.8+ KB

Same procedure for Promo Price

In [495]:
# (Tried converting promo_price to numbers directly -- didn't work, left as a note.)
#pd.to_numeric(df_product['promo_price'])

In [496]:
# Check how many decimal points show up in promo_price.
df_product['promo_price'].str.count(r'\.').value_counts(normalize =  True)

promo_price
1    0.562568
2    0.425421
0    0.012011
Name: proportion, dtype: float64

Check! Is there any pattern in corrupted promo_price w.r.t. price

In [497]:
# Compare the badly-formatted promo_price values against the (already fixed) price column.
numeric_attemp = pd.to_numeric(df_product['promo_price'], errors = 'coerce')
df_product[['promo_price', 'price']][numeric_attemp.isna()].head(20)

    promo_price    price
50    1.119.976   119.00
51   10.449.923  1149.00
66    1.199.957   120.00
67    1.079.961   120.00
97    1.649.896   164.99
100  11.455.917  1199.00
109  16.999.895  1919.00
118  15.989.896  1639.00
127  20.379.897  2039.00
136  20.379.897  2039.00
154  16.999.895  1919.00
163  15.389.905  1613.99
172  15.699.895  1733.99
181  13.855.843  1379.00
190  16.189.897  1619.00
199  14.979.897  1499.00
208  23.989.896  2399.00
217  23.989.896  2399.00
235  25.790.001  2579.00
244  15.755.945  1899.00

Function to shift first decimal to right 2 digits

In [498]:
# Write a function that fixes prices with an extra decimal point, then apply it to promo_price.
def fix_promo_price(s):
    if pd.isna(s):
        return None
    s = str(s)
    dots = s.count('.')

    if dots == 2:
        first_dot_pos = s.index('.')
        digits = s.replace('.', '')
        new_pos = first_dot_pos + 2
        return round(float(digits[:new_pos] + '.' + digits[new_pos:]), 2)
    elif dots == 1:
        return round(float(s) / 10, 2)
    else:
        return round(float(s), 2)

 
df_product['promo_price_fixed'] = df_product['promo_price'].apply(fix_promo_price)

Check! changed values

In [499]:
# Check the fixed promo_price values against the original.
df_product[['promo_price', 'promo_price_fixed', 'price']][numeric_attemp.isna()].head(20)

    promo_price  promo_price_fixed    price
50    1.119.976             112.00   119.00
51   10.449.923            1044.99  1149.00
66    1.199.957             120.00   120.00
67    1.079.961             108.00   120.00
97    1.649.896             164.99   164.99
100  11.455.917            1145.59  1199.00
109  16.999.895            1699.99  1919.00
118  15.989.896            1598.99  1639.00
127  20.379.897            2037.99  2039.00
136  20.379.897            2037.99  2039.00
154  16.999.895            1699.99  1919.00
163  15.389.905            1538.99  1613.99
172  15.699.895            1569.99  1733.99
181  13.855.843            1385.58  1379.00
190  16.189.897            1618.99  1619.00
199  14.979.897            1497.99  1499.00
208  23.989.896            2398.99  2399.00
217  23.989.896            2398.99  2399.00
235  25.790.001            2579.00  2579.00
244  15.755.945            1575.59  1899.00

Check! info() again

In [500]:
# Check the columns one last time.
df_product.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10157 entries, 0 to 19325
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sku                10157 non-null  object
 1   name               10157 non-null  object
 2   desc               10157 non-null  object
 3   price              10157 non-null  float64
 4   promo_price        10157 non-null  object
 5   in_stock           10157 non-null  int64
 6   type               10157 non-null  object
 7   promo_price_fixed  10157 non-null  float64
dtypes: float64(2), int64(1), object(5)
memory usage: 714.2+ KB

In [ ]:
# Save the cleaned products to a new CSV file.
df_product.to_csv('products.clean.csv', index = False)